version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file: .env
    environment:
      WAIT_HOSTS: mongo:27017,redis:6379
      WAIT_HOSTS_TIMEOUT: 36000
    ports:
      - "3500:3500"
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    networks:
      - app-network
    command: sh -c "/wait && yarn start:prod"

  mongo:
    image: mongo:latest
    container_name: database
    restart: unless-stopped
    ports:
      - "27107:27107"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: queue
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
